LOGS = {
    'pine log': {
        'name': 'pine log',
        'xp': 5.0,
        'level': 1,
        'ticks_per_fire': 30,
    },
    'birch log': {
        'name': 'birch log',
        'xp': 12.5,
        'level': 10,
        'ticks_per_fire': 30,
    },
    'maple log': {
        'name': 'maple log',
        'xp': 20.0,
        'level': 15,
        'ticks_per_fire': 30,
    },
    'willow log': {
        'name': 'willow log',
        'xp': 35.0,
        'level': 20,
        'ticks_per_fire': 30,
    },
    'oak log': {
        'name': 'oak log',
        'xp': 55.0,
        'level': 30,
        'ticks_per_fire': 30,
    },
    'elm log': {
        'name': 'elm log',
        'xp': 75.0,
        'level': 40,
        'ticks_per_fire': 30,
    },
    'yew log': {
        'name': 'yew log',
        'xp': 100.0,
        'level': 50,
        'ticks_per_fire': 30,
    },
    'bloodwood log': {
        'name': 'bloodwood log',
        'xp': 125.0,
        'level': 60,
        'ticks_per_fire': 30,
    },
    'ironwood log': {
        'name': 'ironwood log',
        'xp': 150.0,
        'level': 70,
        'ticks_per_fire': 30,
    },
    'ashen log': {
        'name': 'ashen log',
        'xp': 200.0,
        'level': 80,
        'ticks_per_fire': 30,
    },
    'heartwood log': {
        'name': 'heartwood log',
        'xp': 250.0,
        'level': 90,
        'ticks_per_fire': 30,
    },
    'glassthorn log': {
        'name': 'glassthorn log',
        'xp': 325.0,
        'level': 100,
        'ticks_per_fire': 30,
    },
    'emberpine log': {
        'name': 'emberpine log',
        'xp': 400.0,
        'level': 110,
        'ticks_per_fire': 30,
    },
    'ebonspire log': {
        'name': 'ebonspire log',
        'xp': 475.0,
        'level': 120,
        'ticks_per_fire': 30,
    },
}
