

COOKABLES = {
    'shrimp': {
        'name': 'shrimp',
        'items_required': {'raw shrimp': 1},
        'xp': 12.5,
        'level': 1,
        'ticks_per_action': 3,
        'characteristic_level': 10,
        'produce_value': 1.00,
    },
    'anchovy': {
        'name': 'anchovy',
        'items_required': {'raw anchovy': 1},
        'xp': 22.5,
        'level': 10,
        'ticks_per_action': 3,
        'characteristic_level': 20,
        'produce_value': 0.83,
    },
    'trout': {
        'name': 'trout',
        'items_required': {'raw trout': 1},
        'xp': 35.,
        'level': 15,
        'ticks_per_action': 3,
        'characteristic_level': 30,
        'produce_value': 0.69,
    },
    'cod': {
        'name': 'cod',
        'items_required': {'raw cod': 1},
        'xp': 50.,
        'level': 20,
        'ticks_per_action': 3,
        'characteristic_level': 40,
        'produce_value': 0.56,
    },
    'catfish': {
        'name': 'catfish',
        'items_required': {'raw catfish': 1},
        'xp': 65.,
        'level': 30,
        'ticks_per_action': 3,
        'characteristic_level': 50,
        'produce_value': 0.46,
    },
    'bass': {
        'name': 'bass',
        'items_required': {'raw bass': 1},
        'xp': 85.,
        'level': 40,
        'ticks_per_action': 3,
        'characteristic_level': 60,
        'produce_value': 0.37,
    },
}
