name: Run Unit Testing with Pytest

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]

      - name: Lint with Ruff
        run: |
          ruff check --output-format=github --target-version=py313
        continue-on-error: true

      - name: Run tests with pytest
        run: |
          pytest -s --junitxml=junit/test-results.xml --cov-report=xml --cov-report=html
